version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
      - echo Installing npm...
      - curl -sS https://dl.npmpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.npmpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/npm.list
      - apt install --no-install-recommends npm
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
